---

- name: Set hostname
  hostname:
    name: "kube-{{ group_names[0] }}{{ groups[group_names[0]].index(inventory_hostname)+1 }}"

- name: Disable firewall
  ufw:
    state: disabled

- name: Update cache
  apt:
    force_apt_get: yes
    update_cache: yes

- name: Upgrade packages
  apt:
    force_apt_get: yes
    name: "*"
    state: latest

- name: Install packages
  apt:
    force_apt_get: yes
    name:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: Add Docker official GPG key
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

- name: Verify that you now have the key with the fingerprint
  shell: apt-key fingerprint 0EBFCD88

- name: Add Docker-CE repo
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
    state: present

- name: Update cache
  apt:
    force_apt_get: yes
    update_cache: yes

- name: Create dir for docker config
  file:
    path: /etc/docker
    state: directory

- name: Add Docker config file
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json

- name: Install Docker-CE
  apt:
    force_apt_get: yes
    name: docker-ce
    state: present

- name: Enbale Docker-CE bootup
  systemd:
    name: docker.service
    enabled: yes

- name: Add Kubernetes official GPG key
  shell: curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -

- name: Add Kubernetes repo
  copy:
    src: kubernetes.list
    dest: /etc/apt/sources.list.d/kubernetes.list

- name: Update cache
  apt:
    force_apt_get: yes
    update_cache: yes

- name: Install Kubernetes
  apt:
    force_apt_get: yes
    name:
    - kubelet
    - kubeadm
    - kubectl
    state: present

- name: Disable devices and files for paging and swapping
  shell: swapoff -a
